# Generated by Django 5.2.15 on 2026-06-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('idEnfermeiro', models.AutoField(db_column='idEnfermeiro', primary_key=True, serialize=False)),
                ('coren', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Enfermeiro',
                'verbose_name_plural': 'Enfermeiros',
                'db_table': 'Enfermeiro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('idFarmaceutico', models.AutoField(db_column='idFarmaceutico', primary_key=True, serialize=False)),
                ('crf', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Farmacêutico',
                'verbose_name_plural': 'Farmacêuticos',
                'db_table': 'Farmaceutico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('idGestor', models.AutoField(db_column='idGestor', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'db_table': 'Gestor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('idMedico', models.AutoField(db_column='idMedico', primary_key=True, serialize=False)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('especializacao', models.CharField(blank=True, default='', max_length=120)),
                ('idAgenda', models.IntegerField(blank=True, db_column='idAgenda', null=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'Medico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20)),
                ('idRecepcionista', models.AutoField(db_column='idRecepcionista', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
                'db_table': 'Recepcionista',
                'ordering': ['nome'],
            },
        ),
    ]
