"""
Django settings for meu_projeto project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina a variável de ambiente MEDCLIN_SECRET_KEY. O valor abaixo é
# apenas um fallback para desenvolvimento local.
SECRET_KEY = os.environ.get(
    'MEDCLIN_SECRET_KEY',
    'django-insecure-+kxx*#a2cehdegiu-q&07gtkkokgowa@w-672_)2vymp=rw02s',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Algoritmos de hash de senha. Argon2id é o preferido (conforme DA-004 do
# Documento de Arquitetura); os demais permanecem para verificar senhas já
# gravadas com PBKDF2, garantindo compatibilidade com cadastros existentes.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.acesso.apps.AcessoConfig',
    'apps.cadastros.apps.CadastrosConfig',
    'apps.atendimento.apps.AtendimentoConfig',
    'apps.prontuario.apps.ProntuarioConfig',
    'apps.farmacia.apps.FarmaciaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meu_projeto.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.acesso.context_processors.usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'meu_projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Por padrão o projeto usa PostgreSQL, conforme definido na arquitetura.
# Para desenvolvimento e testes locais sem PostgreSQL/psycopg, basta definir
# a variável de ambiente MEDCLIN_DB=sqlite antes de rodar o manage.py:
#     MEDCLIN_DB=sqlite python manage.py migrate
#     MEDCLIN_DB=sqlite python manage.py runserver

if os.environ.get('MEDCLIN_DB', '').lower() == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('MEDCLIN_DB_NAME', 'medclin'),
            'USER': os.environ.get('MEDCLIN_DB_USER', 'medclin_user'),
            'PASSWORD': os.environ.get('MEDCLIN_DB_PASSWORD', 'medclin123'),
            'HOST': os.environ.get('MEDCLIN_DB_HOST', 'localhost'),
            'PORT': os.environ.get('MEDCLIN_DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auditoria / rastreabilidade (concern §2.2.8 do Documento de Arquitetura).
# Em vez de uma tabela (que não consta no Mapeamento Objeto-Relacional), as
# ações relevantes são registradas em arquivo via logging, preservando a
# aderência ao OR. A pasta de logs é criada no startup para o handler funcionar.
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

# E-mail (UC-02 — envio do link de redefinição de senha). Em desenvolvimento, o
# e-mail é impresso no console; em produção, configure um backend SMTP/SES via
# a variável MEDCLIN_EMAIL_BACKEND.
EMAIL_BACKEND = os.environ.get(
    'MEDCLIN_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'MEDCLIN_FROM_EMAIL', 'nao-responder@medclin.local'
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'auditoria': {
            'format': '%(asctime)s | %(message)s',
            'datefmt': '%d/%m/%Y %H:%M:%S',
        },
    },
    'handlers': {
        'auditoria_arquivo': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'auditoria.log'),
            'maxBytes': 1024 * 1024,
            'backupCount': 3,
            'encoding': 'utf-8',
            'formatter': 'auditoria',
        },
    },
    'loggers': {
        'medclin.auditoria': {
            'handlers': ['auditoria_arquivo'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
