# Generated by Django 5.2.15 on 2026-06-15 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(db_column='idAgenda', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horariosProfissionais', models.JSONField(blank=True, db_column='horariosProfissionais', default=dict)),
                ('ocupacaoSalas', models.IntegerField(db_column='ocupacaoSalas', default=0)),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'Agenda',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('idSala', models.IntegerField(blank=True, db_column='idSala', null=True)),
                ('idPaciente', models.IntegerField(db_column='idPaciente')),
                ('idMedico', models.IntegerField(db_column='idMedico')),
                ('idProntuario', models.IntegerField(blank=True, db_column='idProntuario', null=True)),
                ('agenda', models.ForeignKey(blank=True, db_column='idAgenda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='atendimento.agenda')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'Consulta',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionistaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecepcionista', models.IntegerField(db_column='idRecepcionista')),
                ('agenda', models.ForeignKey(db_column='idAgenda', on_delete=django.db.models.deletion.CASCADE, related_name='recepcionistas', to='atendimento.agenda')),
            ],
            options={
                'verbose_name': 'Vínculo recepcionista-agenda',
                'verbose_name_plural': 'Vínculos recepcionista-agenda',
                'db_table': 'Recepcionista_Agenda',
                'unique_together': {('idRecepcionista', 'agenda')},
            },
        ),
    ]
