# Generated by Django 5.2.15 on 2026-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dataPagamento',
            field=models.DateTimeField(blank=True, db_column='dataPagamento', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='formaPagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX')], db_column='formaPagamento', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
