# Generated by Django 5.2.15 on 2026-06-15 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('numeroLote', models.CharField(blank=True, db_column='numeroLote', default='', max_length=50)),
                ('quantidadeEstoque', models.PositiveIntegerField(db_column='quantidadeEstoque', default=0)),
                ('quantidadeMinima', models.PositiveIntegerField(db_column='quantidadeMinima', default=0)),
                ('dataValidade', models.DateField(blank=True, db_column='dataValidade', null=True)),
                ('idMaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'db_table': 'Material',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('numeroLote', models.CharField(blank=True, db_column='numeroLote', default='', max_length=50)),
                ('quantidadeEstoque', models.PositiveIntegerField(db_column='quantidadeEstoque', default=0)),
                ('quantidadeMinima', models.PositiveIntegerField(db_column='quantidadeMinima', default=0)),
                ('dataValidade', models.DateField(blank=True, db_column='dataValidade', null=True)),
                ('idMedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'Medicamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumido',
            fields=[
                ('idConsumo', models.AutoField(db_column='idConsumo', primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('idEnfermeiro', models.IntegerField(db_column='idEnfermeiro')),
                ('dataConsumo', models.DateTimeField(auto_now_add=True, db_column='dataConsumo')),
                ('material', models.ForeignKey(db_column='idMaterial', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='farmacia.material')),
            ],
            options={
                'verbose_name': 'Consumo de material',
                'verbose_name_plural': 'Consumos de material',
                'db_table': 'Material_Consumido',
                'ordering': ['-idConsumo'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoDispensado',
            fields=[
                ('idDispensacao', models.AutoField(db_column='idDispensacao', primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('idFarmaceutico', models.IntegerField(db_column='idFarmaceutico')),
                ('idProntuario', models.IntegerField(blank=True, db_column='idProntuario', null=True)),
                ('dataDispensacao', models.DateTimeField(auto_now_add=True, db_column='dataDispensacao')),
                ('medicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'Dispensação de medicamento',
                'verbose_name_plural': 'Dispensações de medicamento',
                'db_table': 'Medicamento_Dispensado',
                'ordering': ['-idDispensacao'],
            },
        ),
        migrations.CreateModel(
            name='GestorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGestor', models.IntegerField(db_column='idGestor')),
                ('material', models.ForeignKey(db_column='idMaterial', on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='farmacia.material')),
            ],
            options={
                'verbose_name': 'Vínculo gestor-material',
                'verbose_name_plural': 'Vínculos gestor-material',
                'db_table': 'Gestor_Material',
                'unique_together': {('idGestor', 'material')},
            },
        ),
        migrations.CreateModel(
            name='GestorMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGestor', models.IntegerField(db_column='idGestor')),
                ('medicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'Vínculo gestor-medicamento',
                'verbose_name_plural': 'Vínculos gestor-medicamento',
                'db_table': 'Gestor_Medicamento',
                'unique_together': {('idGestor', 'medicamento')},
            },
        ),
    ]
