# Generated by Django 5.2.15 on 2026-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='justificativaReposicao',
            field=models.TextField(blank=True, db_column='justificativaReposicao', default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='quantidadeSolicitada',
            field=models.PositiveIntegerField(blank=True, db_column='quantidadeSolicitada', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='reposicaoSolicitada',
            field=models.BooleanField(db_column='reposicaoSolicitada', default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='justificativaReposicao',
            field=models.TextField(blank=True, db_column='justificativaReposicao', default=''),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='quantidadeSolicitada',
            field=models.PositiveIntegerField(blank=True, db_column='quantidadeSolicitada', null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='reposicaoSolicitada',
            field=models.BooleanField(db_column='reposicaoSolicitada', default=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
